ADDRESS_TYPES = (("home", "Home"), ("billing", "Billing"), ("alternative", "Alternative"))
CONTACT_TYPES = (
    ("email", "Email"),
    ("phone", "Phone"),
    ("mobile", "Mobile"),
)
# We should use django-countries package
EUROPE_COUNTRIES = (
    ("AL", "Albania"),
    ("AD", "Andorra"),
    ("AT", "Austria"),
    ("BY", "Belarus"),
    ("BE", "Belgium"),
    ("BA", "Bosnia and Herzegovina"),
    ("BG", "Bulgaria"),
    ("HR", "Croatia"),
    ("CY", "Cyprus"),
    ("CZ", "Czech Republic"),
    ("DK", "Denmark"),
    ("EE", "Estonia"),
    ("FO", "Faroe Islands"),
    ("FI", "Finland"),
    ("FR", "France"),
    ("DE", "Germany"),
    ("GI", "Gibraltar"),
    ("GR", "Greece"),
    ("HU", "Hungary"),
    ("IS", "Iceland"),
    ("IE", "Ireland"),
    ("IM", "Isle of Man"),
    ("IT", "Italy"),
    ("XK", "Kosovo"),
    ("LV", "Latvia"),
    ("LI", "Liechtenstein"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("MT", "Malta"),
    ("MD", "Moldova"),
    ("MC", "Monaco"),
    ("ME", "Montenegro"),
    ("NL", "Netherlands"),
    ("MK", "North Macedonia"),
    ("NO", "Norway"),
    ("PL", "Poland"),
    ("PT", "Portugal"),
    ("RO", "Romania"),
    ("RU", "Russia"),
    ("SM", "San Marino"),
    ("RS", "Serbia"),
    ("SK", "Slovakia"),
    ("SI", "Slovenia"),
    ("ES", "Spain"),
    ("SE", "Sweden"),
    ("CH", "Switzerland"),
    ("UA", "Ukraine"),
    ("GB", "United Kingdom"),
    ("VA", "Vatican City"),
)

PER_PAGE = 5
