# Generated by Django 4.2.5 on 2023-12-22 11:12

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("transaction_id", models.CharField(max_length=150, unique=True)),
                ("client_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line_1", models.CharField(blank=True, max_length=150, null=True)),
                ("address_line_2", models.CharField(blank=True, max_length=150, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("country_code", django_countries.fields.CountryField(max_length=255, null=True)),
                ("vat_identification_number", models.CharField(blank=True, max_length=20, null=True)),
                ("vat_identification_country", django_countries.fields.CountryField(max_length=255, null=True)),
                ("total_amount_exclude_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount_include_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=7)),
                ("payment_type", models.CharField(default="credit_card", max_length=20)),
                (
                    "transaction_type",
                    models.CharField(choices=[("credit", "Credit"), ("debit", "Debit")], max_length=15),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("document_id", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("quantity", models.PositiveIntegerField(default=1, null=True)),
                ("vat_tax", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("unit_price_excl_vat", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("unit_price_incl_vat", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("organization_code", models.CharField(max_length=255, null=True)),
                ("product_id", models.CharField(blank=True, max_length=50, null=True)),
                ("product_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_items",
                        to="billing.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SageX3TransactionInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("last_status_date", models.DateTimeField(auto_now_add=True)),
                ("retries", models.PositiveIntegerField(default=0)),
                ("input_xml", models.TextField(blank=True, null=True)),
                ("output_xml", models.TextField(blank=True, null=True)),
                ("error_messages", models.TextField(blank=True, null=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sage_x3_transaction_information",
                        to="billing.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
