# Generated by Django 4.2.8 on 2024-03-05 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
