# Generated by Django 4.2.8 on 2024-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_alter_sagex3transactioninformation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionitem",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="organization_code",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="product_code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="product_id",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="unit_price_excl_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="unit_price_incl_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="vat_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
