# Generated by Django 4.2.8 on 2024-03-12 11:02

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_alter_transactionitem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="vat_identification_country",
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True),
        ),
    ]
