# Generated by Django 4.2.8 on 2024-03-22 14:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_sagex3transactioninformation_series_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionitem",
            name="discount",
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_discount_excl_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_discount_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="discount_excl_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="discount_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="country_code",
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True),
        ),
    ]
