version: "3.5"

services:
  database-mysql:
    container_name: nau-database-mysql
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=nau_db
      - MYSQL_USER=nau_user
      - MYSQL_USER_ROOT=root
      - MYSQL_PASSWORD=nau_password
      - MYSQL_ROOT_PASSWORD=nau_password
    hostname: database
    ports:
      - "3306:3306"

  redis:
    hostname: nau-redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    hostname: nau-celery
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A nau_financial_manager worker --loglevel=info
    volumes:
      - ../:/app
    depends_on:
      - database-mysql
      - redis

  celery-beat:
    hostname: nau-celery-beat
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A nau_financial_manager beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DB_HOST=nau-database-mysql
    volumes:
      - ../:/app
    depends_on:
      - database-mysql
      - redis    

  flower:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A nau_financial_manager flower --port=5555
    volumes:
      - ../:/app
    ports:
      - "5555:5555"
    depends_on:
      - database-mysql
      - redis
      - celery

