version: "3.5"

services:
  nau-financial-app:
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ../
      dockerfile: dockers/Dockerfile-dev
    env_file: ../sample-dev.env
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    networks:
      - application_network

networks:
  application_network:
    driver: bridge
