version: "3.5"

services:

  database-psql:
    container_name: nau-database-psql
    restart: always
    image: postgres:15.4
    env_file: ../sample-dev.env
    hostname: database
    ports:
      - "5432:5432"

  nau-financial-app:
    container_name: nau-financial-app
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../sample-dev.env
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    depends_on:
        - database-psql  
