# Generated by Django 4.2.5 on 2023-11-29 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True, verbose_name="Start date")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="End date")),
                (
                    "partner_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.7,
                        max_digits=3,
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Partner percentage",
                    ),
                ),
                ("product_id", models.CharField(max_length=50, verbose_name="Product Id")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_organizations",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue configuration",
                "verbose_name_plural": "Revenue configurations",
            },
        ),
    ]
