# Generated by Django 4.2.5 on 2023-10-13 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared_revenue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueconfiguration",
            name="partner_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.7,
                max_digits=3,
                validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)],
                verbose_name="Value",
            ),
        ),
    ]
