name: Django CI Nau Financial Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Poetry
      run: make install-poetry install-packages

    - name: Run Django tests
      run: make test

    - name: Run Lint
      run: make lint

    - name: Run Django tests on Mysql
      run: make run-database && sleep 30 && make test-mysql
